export const CRYPTO_WATCHLIST = "crypto_watchlist";
export const CRYPTO_COUNT = 20;

export const CRYPTOS = {
      "Bitcoin":"BTC",
      "Ethereum":"ETH",
      "Litecoin": "LTC",
      "Chainlink": "LINK",
      "Bitcoin Cash": "BCH",
      "Stellar Lumens": "XLM",
      "USD Coin": "USDC",
      "Uniswap": "UNI",
      "Aave": "AAVE",
      "Wrapped Bitcoin": "WBTC",
      "EOS": "EOS",
      "Cosmos": "ATOM",
      "Tezos": "XTZ",
      "Synthetix Network Token": "SNX",
      "Maker": "MKR",
      "Compound": "COMP",
      "Dai": "DAI",
      "UMA": "UMA",
      "Dash": "DASH",
      "Filecoin": "FIL",
      "yearn.finance": "YFI",
      "The Graph": "GRT",
      "Zcash": "ZEC",
      "Ox": "ZRX",
      "Algorand": "ALGO",
      "Ren": "REN",
      "Loopring": "LRC",
      "OMG Network": "OMG",
      "Celo": "CGLD",
      "Basic Attention Token": "BAT",
      "Keyber Network": "KNC",
      "Decentraland": "MANA",
      "Bancor Network Token": "BNT",
      "Balancer": "BAL",
      "Band Protocol": "BAND",
      "NuCypher": "NU",
      "Civic": "CVC",
      "Numeraire": "NMR",
      "Orchid": "OXT",
      "districtOx": "DNT"
};
